### ISSUE TITLE
The v1.register method should return a VeresOneDidDoc

### ISSUE THREAD

**Issue by gannan08** [digitalbazaar/did-io#33] opened 2018-10-11 17:23 UTC
Currently, the method returns an axios response and it should return a Promise that resolves to a veres one did doc or throw an error.

https://github.com/digitalbazaar/did-io/blob/development/lib/methods/veres-one/veres-one.js#L169

**Comment by dmitrizagidulin** [comment] 2018-10-11 17:34
@gannan08 are you sure? The thing about register() is that it requires an already generated DID Doc to be passed in. What would be the point of returning it? (It's immutable.)
The reason it's returning an axios response is so that the calling code can judge success/failure.

**Comment by mattcollier** [comment] 2018-10-11 17:38
@dmitrizagidulin there were some test written against this API that were working before largely based on this documentation: https://github.com/digitalbazaar/did-io#generating-and-registering-a-veres-one-did-document

Perhaps returning the did document is optional, but throwing an error on failure is a requirement.  Discerning a failure condition based on axios response is did-io's job IMO.

**Comment by dmitrizagidulin** [comment] 2018-10-11 17:44
> Discerning a failure condition based on axios response is did-io's job IMO.

Sure, agreed. I was thinking more about app-level logic failures (like, the ledger saying "your accelerator proof didn't check out"), which are less the domain of axios? Or are you thinking like, those kind of errors should return as status 400 anyways, in which case axios will throw em? In which case, yeah.

>  there were some test written against this API that were working before

Wait, did the tests break now, or..?

**Comment by dmitrizagidulin** [comment] 2018-10-11 17:46
Ok wait, my apologies, guys. I was confused, I thought we were talking about VeresOneDidDoc.generate(), not VeresOne.generate().

Does it not already return a Did doc?

**Comment by mattcollier** [comment] 2018-10-11 17:47
The test in question was patched earlier today, it passes like this: https://github.com/veres-one/veres-one/commit/3a69c0445b940c49c6a27c0c0c8cefa9dbffe217

We would like it to be restored to it's former self.

**Comment by mattcollier** [comment] 2018-10-11 17:50
We're talking about the `register` API.  :)

**Comment by dmitrizagidulin** [comment] 2018-10-11 17:50
> We would like it to be restored to it's former self.

Ok. So you'd like register() to return the did doc, makes sense. 

Do you foresee any need for the register call results from the ledger? 

> We're talking about the register API.

Riiight, ok, I was meta-confused :)

**Comment by mattcollier** [comment] 2018-10-11 17:56
If the concern is that we might need to float axios errors up the stack, maybe something along these lines is appropriate? https://github.com/digitalbazaar/http-signature-header/blob/master/lib/HttpSignatureError.js

So, I would think that if the HTTP API returns some json schema validation error (for instance), the caller of did-io would need to have access to that information to address the cause of the failure.

**Comment by dmitrizagidulin** [comment] 2018-10-11 18:07
@mattcollier So the errors I could see - they'll propagate like exceptions usually do. 
What about successes? Do you foresee any need for the success results?

**Comment by mattcollier** [comment] 2018-10-11 18:10
Are there different flavors of success?  Are we speaking about the `register` API specifically or did-io APIs generally?

**Comment by dmitrizagidulin** [comment] 2018-10-11 18:11
I don't know, re different flavors of success. :) (And yeah, talking specifically about the `register` API).

Tell you what, I'm cool with just having it return a did doc, and discarding the register results, for now. If we need em later, we can refactor.

**Comment by gannan08** [comment] 2018-10-11 18:51
To understand this correctly if the server returns a 204 (Success) we will be returning a did doc, else throw an error?

**Comment by dmitrizagidulin** [comment] 2018-10-11 19:12
> To understand this correctly if the server returns a 204 (Success) we will be returning a did doc, else throw an error?

Right!

**Comment by dmitrizagidulin** [comment] 2018-10-11 20:53
Merged, closing.

**Closed as completed by dmitrizagidulin** 2018-10-11 20:53 UTC
